name: Assign issues to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Assign to project
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/users/srnyx/projects/3'
        column_name: 'Not started'
